### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shisushi** [kikkia/BotDO#17]
Sorry to bother you here but I didn't know how else to ask. Are you still working on the BDO bot? If so, do you have any dates for the planned features? If not, could you please at least add the new classes such as Maegu to the list. Lastly, is there any chance of having the bot registered on more than 100 servers? A couple of guilds I know would love to implement it in their discords but currently can't as the limit has been reached. Thanks❤

**Comment by kikkia** [comment]
Hey there, unfortunately approval would involve quite a bit of rework. I am working on purging out some small servers https://discord.com/oauth2/authorize?client_id=797767418285260802&scope=bot&permissions=2084039792 Feel free to try

If I do make any major change, it will be one that has the bot leave if a guild doesnt use it for a certain period of time. Thanks for using it though :)
